import type { Metadata } from "next";
import { Geist, Geist_Mono, New_Rocker, Poppins } from "next/font/google";
import "./globals.css";
import Header from "@/components/all-pages/Header";
import Footer from "@/components/all-pages/Footer";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

const rocker = New_Rocker({
  variable: "--font-new-rocker",
  subsets: ["latin"],
  weight: "400"
});

const poppins = Poppins({
  variable: "--font-poppins",
  subsets: ["latin"],
  weight: "400"
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className="scroll-smooth">
      <body
        className={`${geistSans.variable} ${geistMono.variable} ${rocker.variable} ${poppins.variable} ${poppins.variable} text-text bg-white text-inherit antialiased`}
      >
        <Header/>
        {children}
        <Footer/>
      </body>
    </html>
  );
}
